[workspace]
resolver = "2"
members = ["crates/core", "crates/cli"]

[workspace.package]
version = "0.4.3"
edition = "2021"
authors = ["Andrew Chen <hello@andrewtheguy.com>"]

[workspace.dependencies]
audio-pattern-detector-core = { path = "crates/core" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
tempfile = "3"

[profile.release]
lto = "thin"
