# Minimal stub for matplotlib.pyplot
from typing import Any

def figure(figsize: tuple[int, int] | None = None) -> Any: ...
def plot(*args: Any, **kwargs: Any) -> Any: ...
def title(s: str) -> None: ...
def xlabel(s: str) -> None: ...
def ylabel(s: str) -> None: ...
def savefig(fname: str) -> None: ...
def close() -> None: ...
def scatter(*args: Any, **kwargs: Any) -> Any: ...
def ylim(*args: Any, **kwargs: Any) -> Any: ...
